/*
 * Generated by ISE 16.05.9.8969 GPL Edition - macosx-x86-64
 */

#include "eif_eiffel.h"
#include "eif_project.h"
#include "egc_include.h"

#ifdef __cplusplus
extern "C" {
#endif
extern void F1_23();
extern EIF_REFERENCE F1_14();
extern void F272_5393();
extern void F276_5657();
extern void F270_5319();
extern void F275_5566();
extern void F454_4503();
extern void F359_5199();
extern void F72_1142();
extern EIF_REFERENCE F72_1129();
extern EIF_BOOLEAN F72_1141();
extern EIF_BOOLEAN F72_1146();
extern void F72_1151();
extern void F72_1152();
extern void F72_1153();
extern void F109_1638();
extern EIF_TYPED_VALUE F109_1639();

long *eif_area_table = (long *)0;
long *eif_lower_table = (long *)0;


extern void egc_init_plug (void); 
void egc_init_plug (void)
{
	egc_prof_enabled = (EIF_INTEGER) 0;
	egc_correct_mismatch = (void (*)(EIF_REFERENCE)) F1_23;
	egc_twin = (EIF_TYPED_VALUE (*)(EIF_REFERENCE)) F1_14;
	egc_strmake = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F272_5393;
	egc_str32make = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F270_5319;
	egc_arrmake = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F454_4503;
	egc_strset = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F276_5657;
	egc_str32set = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F275_5566;
	egc_routdisp_wb = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F359_5199;
	egc_is_scoop_capable = 0;
	egc_set_exception_data = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F72_1142;
	egc_set_last_exception = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F72_1141;
	egc_last_exception = (EIF_TYPED_VALUE (*)(EIF_REFERENCE)) F72_1129;
	egc_is_code_ignored = (EIF_TYPED_VALUE (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F72_1146;
	egc_once_raise = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F72_1151;
	egc_init_exception_manager = (void (*)(EIF_REFERENCE)) F72_1152;
	egc_free_preallocated_trace = (void (*)(EIF_REFERENCE)) F72_1153;

	egc_str_dtype = 275;

	egc_str32_dtype = 274;
	egc_arr_dtype = 453;
	egc_tup_dtype = 254;
	egc_disp_rout_id = 2027;
	egc_copy_rout_id = 18;
	egc_is_equal_rout_id = 11;

	egc_sp_char = 0x02CC;
	egc_sp_wchar = 0x01E0;
	egc_sp_bool = 0x02DE;
	egc_sp_uint8 = 0x0222;
	egc_sp_uint16 = 0x02A9;
	egc_sp_uint32 = 0x0286;
	egc_sp_uint64 = 0x01F6;
	egc_sp_int8 = 0xFFFF;
	egc_sp_int16 = 0xFFFF;
	egc_sp_int32 = 0x017D;
	egc_sp_int64 = 0xFFFF;
	egc_sp_real32 = 0x0339;
	egc_sp_real64 = 0x035C;
	egc_sp_pointer = 0x0316;
	egc_sp_ref = 0x01C1;

	egc_uint8_dtype = 316;
	egc_uint16_dtype = 313;
	egc_uint32_dtype = 310;
	egc_uint64_dtype = 307;
	egc_int8_dtype = 304;
	egc_int16_dtype = 301;
	egc_int32_dtype = 298;
	egc_int64_dtype = 325;
	egc_bool_dtype = 262;
	egc_real32_dtype = 319;
	egc_char_dtype = 259;
	egc_wchar_dtype = 256;
	egc_real64_dtype = 322;
	egc_point_dtype = 265;

	egc_exception_dtype = 121;
	egc_except_emnger_dtype = 71;

	egc_ce_type = egc_ce_type_init;

	egc_ce_exp_type = egc_ce_exp_type_init;
	egc_fsystem = egc_fsystem_init;
	egc_system_mod_init = egc_system_mod_init_init;
	egc_partab = egc_partab_init;
	egc_partab_size = egc_partab_size_init;
	egc_foption = egc_foption_init;
	egc_frozen = egc_frozen_init;
	egc_fpatidtab = egc_fpatidtab_init;
	egc_address_table = egc_address_table_init;
	egc_fpattern = egc_fpattern_init;

	egc_einit = egc_einit_init;
	egc_tabinit = egc_tabinit_init;
	egc_forg_table = egc_forg_table_init;

	egc_system_name = "web_annual_reports";
	egc_system_location = "/Users/rakZeee/course_project/course_project-frames/EIFGENs/web_annual_reports/W_code";
	egc_compiler_tag = 38;
	egc_project_version = 1491824354;
	egc_has_old_special_semantic = 0;
	egc_has_ieee_semantic = 1;
	scount = 1005;

	egc_rcount = 1;
	egc_ridx = 0;
	egc_rlist = (char**) eif_malloc (sizeof(char*)*egc_rcount);
	egc_rcdt = (int32 *) eif_malloc (sizeof(int32)*egc_rcount);
	egc_rcrid = (int32 *) eif_malloc (sizeof(int32)*egc_rcount);
	egc_rcarg = (int32 *) eif_malloc (sizeof(int32)*egc_rcount);
	egc_rlist[0] = "WEB_ANNUAL_REPORTS.make_and_launch";
	egc_rcdt[0] = 0;
	egc_rcrid[0] = 1042;
	egc_rcarg[0] = 0;
	
	
	egc_platform_level = 0x00000D00;
	egc_rt_extension_dt = 108;
	egc_rt_extension_notify = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F109_1638;
	egc_rt_extension_notify_argument = (EIF_TYPED_VALUE (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F109_1639;
}

void egc_rcdt_init (void)
{
	if (egc_rcdt[0] == 0) {
		egc_rcdt[0] = 175; /* WEB_ANNUAL_REPORTS */
	}
}

#ifdef __cplusplus
}
#endif
